spring.application.name=store
spring.datasource.url=jdbc:mysql://localhost:3306/aijaz
spring.datasource.username=root
spring.datasource.password=AIJAZ@12345612
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=ZWNvbW1lcmNlLXN0b3JlLWp3dC1zZWNyZXQta2V5LWZvci1sb2NhbC1kZXZlbG9wbWVudC0xMjM0NTY3ODkw
app.jwt.expiration=86400000

server.port=8080
